# -*- coding: utf-8 -*-
"""FPgrowth_Algorithm_1_sem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14yQxIc3vI0CWEGgw28WS44DMjoTWZNgw

"""

"""Importing Libraries:"""

import pandas as pd
import numpy as np
from scipy import sparse
from sklearn.metrics.pairwise import cosine_similarity

"""Preparing the Data"""

df = pd.read_excel('Student_Performance_Data.xlsx', sheet_name='Sheet1')
df.head()

df_dict_sem = {}
for name in df['Semster_Name'].unique():
    df_dict_sem[name] = df[df['Semster_Name'] == name].reset_index(drop=True)
df_dict_sem

"""Preparing Data for one Semester: (>Marks Threshold Accepted)"""

marks_thresh = 75

df_sem_1 = df_dict_sem['Sem_1']
df_sem_1.head()

#Applying Marks Threshold
df_sem_1_marks_thresh = df_sem_1[df_sem_1['Marks'] > marks_thresh].reset_index(drop=True)
df_sem_1_marks_thresh.head()

#getting only the sudent ID and the paper name
df_sem_1_marks_thresh_ID_Paper = df_sem_1_marks_thresh[['Student_ID', 'Paper_Name']]
df_sem_1_marks_thresh_ID_Paper

from fpgrowth_py import fpgrowth


df_sem_1_encoded = df_sem_1_marks_thresh_ID_Paper.groupby(['Student_ID'], axis=0)['Paper_Name'].transform(lambda x : ','.join(x))
df_sem_1_encoded.head()

sem_1_itemlist = [value.split(',') for value in df_sem_1_encoded.values.tolist()]
sem_1_itemlist

minsup = float(input('Enter Minimum Support (0.2) : '))
minconf = float(input('Enter Minimum Confidence (0.48) : '))

freqItemSet_sem1, rules_sem1 = fpgrowth(sem_1_itemlist, minsup, minconf)

print(freqItemSet_sem1)
print()
print()
print(rules_sem1)
